package org.ionkin.hl7.fhir.model.ucum

import org.apache.commons.csv.{CSVFormat, CSVParser}
import org.ionkin.hl7.fhir.model.{Code, Uri}

import scala.collection.mutable
import scala.io.Source

object CurrencyMain extends App {
  case class Model(currency: String, alphCode: String) {
    def name: String = currency.replaceAll("\\W", "")
    def isValid: Boolean = alphCode.trim.nonEmpty
    override def toString: String = s"""  lazy val ${name} = new Currency(new Code("${alphCode}"), "${currency}")"""
  }
  import scala.collection.JavaConverters._
  val csvData = Source.fromResource("currency.csv").getLines.mkString("\n")
  val parser = CSVParser.parse(csvData, CSVFormat.RFC4180)
  val records = parser.getRecords.asScala
  val models = mutable.Buffer[Model]()
  for (r <- records) {
    models += Model(r.get(1), r.get(2))
  }
  println("object Currency extends Enumeration {")
  println("  type Currency = Value")
  models.distinct.filter(_.isValid).foreach(println)
  println("}")
}

case class Currency(code: Code, display: String) {
  def system: Uri = new Uri("urn:iso:std:iso:4217")
}

object Currency {
  lazy val Afghani = new Currency(new Code("AFN"), "Afghani")
  lazy val Euro = new Currency(new Code("EUR"), "Euro")
  lazy val Lek = new Currency(new Code("ALL"), "Lek")
  lazy val AlgerianDinar = new Currency(new Code("DZD"), "Algerian Dinar")
  lazy val USDollar = new Currency(new Code("USD"), "US Dollar")
  lazy val Kwanza = new Currency(new Code("AOA"), "Kwanza")
  lazy val EastCaribbeanDollar = new Currency(new Code("XCD"), "East Caribbean Dollar")
  lazy val ArgentinePeso = new Currency(new Code("ARS"), "Argentine Peso")
  lazy val ArmenianDram = new Currency(new Code("AMD"), "Armenian Dram")
  lazy val ArubanFlorin = new Currency(new Code("AWG"), "Aruban Florin")
  lazy val AustralianDollar = new Currency(new Code("AUD"), "Australian Dollar")
  lazy val AzerbaijanManat = new Currency(new Code("AZN"), "Azerbaijan Manat")
  lazy val BahamianDollar = new Currency(new Code("BSD"), "Bahamian Dollar")
  lazy val BahrainiDinar = new Currency(new Code("BHD"), "Bahraini Dinar")
  lazy val Taka = new Currency(new Code("BDT"), "Taka")
  lazy val BarbadosDollar = new Currency(new Code("BBD"), "Barbados Dollar")
  lazy val BelarusianRuble = new Currency(new Code("BYN"), "Belarusian Ruble")
  lazy val BelizeDollar = new Currency(new Code("BZD"), "Belize Dollar")
  lazy val CFAFrancBCEAO = new Currency(new Code("XOF"), "CFA Franc BCEAO")
  lazy val BermudianDollar = new Currency(new Code("BMD"), "Bermudian Dollar")
  lazy val IndianRupee = new Currency(new Code("INR"), "Indian Rupee")
  lazy val Ngultrum = new Currency(new Code("BTN"), "Ngultrum")
  lazy val Boliviano = new Currency(new Code("BOB"), "Boliviano")
  lazy val Mvdol = new Currency(new Code("BOV"), "Mvdol")
  lazy val ConvertibleMark = new Currency(new Code("BAM"), "Convertible Mark")
  lazy val Pula = new Currency(new Code("BWP"), "Pula")
  lazy val NorwegianKrone = new Currency(new Code("NOK"), "Norwegian Krone")
  lazy val BrazilianReal = new Currency(new Code("BRL"), "Brazilian Real")
  lazy val BruneiDollar = new Currency(new Code("BND"), "Brunei Dollar")
  lazy val BulgarianLev = new Currency(new Code("BGN"), "Bulgarian Lev")
  lazy val BurundiFranc = new Currency(new Code("BIF"), "Burundi Franc")
  lazy val CaboVerdeEscudo = new Currency(new Code("CVE"), "Cabo Verde Escudo")
  lazy val Riel = new Currency(new Code("KHR"), "Riel")
  lazy val CFAFrancBEAC = new Currency(new Code("XAF"), "CFA Franc BEAC")
  lazy val CanadianDollar = new Currency(new Code("CAD"), "Canadian Dollar")
  lazy val CaymanIslandsDollar = new Currency(new Code("KYD"), "Cayman Islands Dollar")
  lazy val ChileanPeso = new Currency(new Code("CLP"), "Chilean Peso")
  lazy val UnidaddeFomento = new Currency(new Code("CLF"), "Unidad de Fomento")
  lazy val YuanRenminbi = new Currency(new Code("CNY"), "Yuan Renminbi")
  lazy val ColombianPeso = new Currency(new Code("COP"), "Colombian Peso")
  lazy val UnidaddeValorReal = new Currency(new Code("COU"), "Unidad de Valor Real")
  lazy val ComorianFranc = new Currency(new Code("KMF"), "Comorian Franc ")
  lazy val CongoleseFranc = new Currency(new Code("CDF"), "Congolese Franc")
  lazy val NewZealandDollar = new Currency(new Code("NZD"), "New Zealand Dollar")
  lazy val CostaRicanColon = new Currency(new Code("CRC"), "Costa Rican Colon")
  lazy val Kuna = new Currency(new Code("HRK"), "Kuna")
  lazy val CubanPeso = new Currency(new Code("CUP"), "Cuban Peso")
  lazy val PesoConvertible = new Currency(new Code("CUC"), "Peso Convertible")
  lazy val NetherlandsAntilleanGuilder = new Currency(new Code("ANG"), "Netherlands Antillean Guilder")
  lazy val CzechKoruna = new Currency(new Code("CZK"), "Czech Koruna")
  lazy val DanishKrone = new Currency(new Code("DKK"), "Danish Krone")
  lazy val DjiboutiFranc = new Currency(new Code("DJF"), "Djibouti Franc")
  lazy val DominicanPeso = new Currency(new Code("DOP"), "Dominican Peso")
  lazy val EgyptianPound = new Currency(new Code("EGP"), "Egyptian Pound")
  lazy val ElSalvadorColon = new Currency(new Code("SVC"), "El Salvador Colon")
  lazy val Nakfa = new Currency(new Code("ERN"), "Nakfa")
  lazy val EthiopianBirr = new Currency(new Code("ETB"), "Ethiopian Birr")
  lazy val FalklandIslandsPound = new Currency(new Code("FKP"), "Falkland Islands Pound")
  lazy val FijiDollar = new Currency(new Code("FJD"), "Fiji Dollar")
  lazy val CFPFranc = new Currency(new Code("XPF"), "CFP Franc")
  lazy val Dalasi = new Currency(new Code("GMD"), "Dalasi")
  lazy val Lari = new Currency(new Code("GEL"), "Lari")
  lazy val GhanaCedi = new Currency(new Code("GHS"), "Ghana Cedi")
  lazy val GibraltarPound = new Currency(new Code("GIP"), "Gibraltar Pound")
  lazy val Quetzal = new Currency(new Code("GTQ"), "Quetzal")
  lazy val PoundSterling = new Currency(new Code("GBP"), "Pound Sterling")
  lazy val GuineanFranc = new Currency(new Code("GNF"), "Guinean Franc")
  lazy val GuyanaDollar = new Currency(new Code("GYD"), "Guyana Dollar")
  lazy val Gourde = new Currency(new Code("HTG"), "Gourde")
  lazy val Lempira = new Currency(new Code("HNL"), "Lempira")
  lazy val HongKongDollar = new Currency(new Code("HKD"), "Hong Kong Dollar")
  lazy val Forint = new Currency(new Code("HUF"), "Forint")
  lazy val IcelandKrona = new Currency(new Code("ISK"), "Iceland Krona")
  lazy val Rupiah = new Currency(new Code("IDR"), "Rupiah")
  lazy val SDRSpecialDrawingRight = new Currency(new Code("XDR"), "SDR (Special Drawing Right)")
  lazy val IranianRial = new Currency(new Code("IRR"), "Iranian Rial")
  lazy val IraqiDinar = new Currency(new Code("IQD"), "Iraqi Dinar")
  lazy val NewIsraeliSheqel = new Currency(new Code("ILS"), "New Israeli Sheqel")
  lazy val JamaicanDollar = new Currency(new Code("JMD"), "Jamaican Dollar")
  lazy val Yen = new Currency(new Code("JPY"), "Yen")
  lazy val JordanianDinar = new Currency(new Code("JOD"), "Jordanian Dinar")
  lazy val Tenge = new Currency(new Code("KZT"), "Tenge")
  lazy val KenyanShilling = new Currency(new Code("KES"), "Kenyan Shilling")
  lazy val NorthKoreanWon = new Currency(new Code("KPW"), "North Korean Won")
  lazy val Won = new Currency(new Code("KRW"), "Won")
  lazy val KuwaitiDinar = new Currency(new Code("KWD"), "Kuwaiti Dinar")
  lazy val Som = new Currency(new Code("KGS"), "Som")
  lazy val LaoKip = new Currency(new Code("LAK"), "Lao Kip")
  lazy val LebanesePound = new Currency(new Code("LBP"), "Lebanese Pound")
  lazy val Loti = new Currency(new Code("LSL"), "Loti")
  lazy val Rand = new Currency(new Code("ZAR"), "Rand")
  lazy val LiberianDollar = new Currency(new Code("LRD"), "Liberian Dollar")
  lazy val LibyanDinar = new Currency(new Code("LYD"), "Libyan Dinar")
  lazy val SwissFranc = new Currency(new Code("CHF"), "Swiss Franc")
  lazy val Pataca = new Currency(new Code("MOP"), "Pataca")
  lazy val Denar = new Currency(new Code("MKD"), "Denar")
  lazy val MalagasyAriary = new Currency(new Code("MGA"), "Malagasy Ariary")
  lazy val MalawiKwacha = new Currency(new Code("MWK"), "Malawi Kwacha")
  lazy val MalaysianRinggit = new Currency(new Code("MYR"), "Malaysian Ringgit")
  lazy val Rufiyaa = new Currency(new Code("MVR"), "Rufiyaa")
  lazy val Ouguiya = new Currency(new Code("MRU"), "Ouguiya")
  lazy val MauritiusRupee = new Currency(new Code("MUR"), "Mauritius Rupee")
  lazy val ADBUnitofAccount = new Currency(new Code("XUA"), "ADB Unit of Account")
  lazy val MexicanPeso = new Currency(new Code("MXN"), "Mexican Peso")
  lazy val MexicanUnidaddeInversionUDI = new Currency(new Code("MXV"), "Mexican Unidad de Inversion (UDI)")
  lazy val MoldovanLeu = new Currency(new Code("MDL"), "Moldovan Leu")
  lazy val Tugrik = new Currency(new Code("MNT"), "Tugrik")
  lazy val MoroccanDirham = new Currency(new Code("MAD"), "Moroccan Dirham")
  lazy val MozambiqueMetical = new Currency(new Code("MZN"), "Mozambique Metical")
  lazy val Kyat = new Currency(new Code("MMK"), "Kyat")
  lazy val NamibiaDollar = new Currency(new Code("NAD"), "Namibia Dollar")
  lazy val NepaleseRupee = new Currency(new Code("NPR"), "Nepalese Rupee")
  lazy val CordobaOro = new Currency(new Code("NIO"), "Cordoba Oro")
  lazy val Naira = new Currency(new Code("NGN"), "Naira")
  lazy val RialOmani = new Currency(new Code("OMR"), "Rial Omani")
  lazy val PakistanRupee = new Currency(new Code("PKR"), "Pakistan Rupee")
  lazy val Balboa = new Currency(new Code("PAB"), "Balboa")
  lazy val Kina = new Currency(new Code("PGK"), "Kina")
  lazy val Guarani = new Currency(new Code("PYG"), "Guarani")
  lazy val Sol = new Currency(new Code("PEN"), "Sol")
  lazy val PhilippinePeso = new Currency(new Code("PHP"), "Philippine Peso")
  lazy val Zloty = new Currency(new Code("PLN"), "Zloty")
  lazy val QatariRial = new Currency(new Code("QAR"), "Qatari Rial")
  lazy val RomanianLeu = new Currency(new Code("RON"), "Romanian Leu")
  lazy val RussianRuble = new Currency(new Code("RUB"), "Russian Ruble")
  lazy val RwandaFranc = new Currency(new Code("RWF"), "Rwanda Franc")
  lazy val SaintHelenaPound = new Currency(new Code("SHP"), "Saint Helena Pound")
  lazy val Tala = new Currency(new Code("WST"), "Tala")
  lazy val Dobra = new Currency(new Code("STN"), "Dobra")
  lazy val SaudiRiyal = new Currency(new Code("SAR"), "Saudi Riyal")
  lazy val SerbianDinar = new Currency(new Code("RSD"), "Serbian Dinar")
  lazy val SeychellesRupee = new Currency(new Code("SCR"), "Seychelles Rupee")
  lazy val Leone = new Currency(new Code("SLL"), "Leone")
  lazy val SingaporeDollar = new Currency(new Code("SGD"), "Singapore Dollar")
  lazy val Sucre = new Currency(new Code("XSU"), "Sucre")
  lazy val SolomonIslandsDollar = new Currency(new Code("SBD"), "Solomon Islands Dollar")
  lazy val SomaliShilling = new Currency(new Code("SOS"), "Somali Shilling")
  lazy val SouthSudanesePound = new Currency(new Code("SSP"), "South Sudanese Pound")
  lazy val SriLankaRupee = new Currency(new Code("LKR"), "Sri Lanka Rupee")
  lazy val SudanesePound = new Currency(new Code("SDG"), "Sudanese Pound")
  lazy val SurinamDollar = new Currency(new Code("SRD"), "Surinam Dollar")
  lazy val Lilangeni = new Currency(new Code("SZL"), "Lilangeni")
  lazy val SwedishKrona = new Currency(new Code("SEK"), "Swedish Krona")
  lazy val WIREuro = new Currency(new Code("CHE"), "WIR Euro")
  lazy val WIRFranc = new Currency(new Code("CHW"), "WIR Franc")
  lazy val SyrianPound = new Currency(new Code("SYP"), "Syrian Pound")
  lazy val NewTaiwanDollar = new Currency(new Code("TWD"), "New Taiwan Dollar")
  lazy val Somoni = new Currency(new Code("TJS"), "Somoni")
  lazy val TanzanianShilling = new Currency(new Code("TZS"), "Tanzanian Shilling")
  lazy val Baht = new Currency(new Code("THB"), "Baht")
  lazy val Paanga = new Currency(new Code("TOP"), "Pa’anga")
  lazy val TrinidadandTobagoDollar = new Currency(new Code("TTD"), "Trinidad and Tobago Dollar")
  lazy val TunisianDinar = new Currency(new Code("TND"), "Tunisian Dinar")
  lazy val TurkishLira = new Currency(new Code("TRY"), "Turkish Lira")
  lazy val TurkmenistanNewManat = new Currency(new Code("TMT"), "Turkmenistan New Manat")
  lazy val UgandaShilling = new Currency(new Code("UGX"), "Uganda Shilling")
  lazy val Hryvnia = new Currency(new Code("UAH"), "Hryvnia")
  lazy val UAEDirham = new Currency(new Code("AED"), "UAE Dirham")
  lazy val USDollarNextday = new Currency(new Code("USN"), "US Dollar (Next day)")
  lazy val PesoUruguayo = new Currency(new Code("UYU"), "Peso Uruguayo")
  lazy val UruguayPesoenUnidadesIndexadasUI = new Currency(new Code("UYI"), "Uruguay Peso en Unidades Indexadas (UI)")
  lazy val UnidadPrevisional = new Currency(new Code("UYW"), "Unidad Previsional")
  lazy val UzbekistanSum = new Currency(new Code("UZS"), "Uzbekistan Sum")
  lazy val Vatu = new Currency(new Code("VUV"), "Vatu")
  lazy val BolvarSoberano = new Currency(new Code("VES"), "Bolívar Soberano")
  lazy val Dong = new Currency(new Code("VND"), "Dong")
  lazy val YemeniRial = new Currency(new Code("YER"), "Yemeni Rial")
  lazy val ZambianKwacha = new Currency(new Code("ZMW"), "Zambian Kwacha")
  lazy val ZimbabweDollar = new Currency(new Code("ZWL"), "Zimbabwe Dollar")
  lazy val BondMarketsUnitEuropeanCompositeUnitEURCO = new Currency(new Code("XBA"), "Bond Markets Unit European Composite Unit (EURCO)")
  lazy val BondMarketsUnitEuropeanMonetaryUnitEMU6 = new Currency(new Code("XBB"), "Bond Markets Unit European Monetary Unit (E.M.U.-6)")
  lazy val BondMarketsUnitEuropeanUnitofAccount9EUA9 = new Currency(new Code("XBC"), "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)")
  lazy val BondMarketsUnitEuropeanUnitofAccount17EUA17 = new Currency(new Code("XBD"), "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)")
  lazy val Codesspecificallyreservedfortestingpurposes = new Currency(new Code("XTS"), "Codes specifically reserved for testing purposes")
  lazy val Thecodesassignedfortransactionswherenocurrencyisinvolved = new Currency(new Code("XXX"), "The codes assigned for transactions where no currency is involved")
  lazy val Gold = new Currency(new Code("XAU"), "Gold")
  lazy val Palladium = new Currency(new Code("XPD"), "Palladium")
  lazy val Platinum = new Currency(new Code("XPT"), "Platinum")
  lazy val Silver = new Currency(new Code("XAG"), "Silver")
}
